owner: hds-solutions
repo: status.Presupuesta.me
user-agent: "Presupuesta.me Upptime Checker"

sites:
  - name: Presupuesta.me
    url: https://staging.presupuesta.me/up
    headers:
      - "User-Agent: Presupuesta.me Upptime"
    maxResponseTime: 5000

assignees:
  - $OWNER

status-website:
  name: Presupuesta.me Status
  cname: status.presupuesta.me
  logoUrl: https://hds-solutions.net/build/assets/favicon-Ddt1gdk2.ico
  theme: night
  introTitle: "Status page for **[Presupuesta.me](https://presupuesta.me)**"
  navbar:
    - title: Home
      href: https://staging.presupuesta.me
    - title: Status
      href: /

i18n:
  footer: "[HDS Solutions](https://hds-solutions.net) &copy; 2024 Todos los derechos reservados, powered by [Upptime](https://upptime.js.org)"
